### ISSUE TITLE
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 9)

### ISSUE THREAD

**Issue by citrusoft** [MichinariNukazawa/debian_package_c_application_automate_example#1]
I fixed this issue on uname -a
Linux vagrant 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

sudo apt-get install debhelper dh-virtualenv

**Comment by ChunhThanhDe** [comment]
## Build Error: Unmet Dependencies in `cuttlefish-frontend`

I went to download Cuttlefish and got this error

### Error Description:
During the build process of `cuttlefish-frontend`, the following issues occurred:

```bash
After this operation, 9.216 B disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 382106 files and directories currently installed.)
Removing cuttlefish-frontend-build-deps (1.0.0) ...
mk-build-deps: Unable to install cuttlefish-frontend-build-deps at /usr/bin/mk-build-deps line 402.
mk-build-deps: Unable to install all build-dep packages
dpkg-buildpackage: info: source package cuttlefish-frontend
dpkg-buildpackage: info: source version 1.0.0
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Jorge Moreira <jemoreira@google.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build frontend
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper-compat (= 12) golang (>= 2:1.13~) | golang-1.13 libprotobuf-dev protobuf-compiler
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```

### Issues Encountered:
1. **Dependency Issues**: 
   - `debhelper-compat (= 12)` is required but missing.
   - `golang (>= 2:1.13~)` or `golang-1.13` is needed.
   - `libprotobuf-dev` and `protobuf-compiler` are also missing.

2. **Build Aborted**: 
   The build process is aborted due to unmet dependencies.

### System Information:
- **Source package**: `cuttlefish-frontend`
- **Source version**: 1.0.0
- **Architecture**: amd64
- **Build Environment**: Ubuntu 18.04

---

I can't find any official documentation for installing debhelper-compat (= 12) on ubuntu 18.04 at the moment.

Does anyone have a solution for resolving these unmet dependencies or alternative suggestions to bypass this issue?

**Comment by AduosPiggy** [comment]
me too,bro

**Comment by ChunhThanhDe** [comment]
@AduosPiggy  upgrade to ubuntu 20 bro, it will solve xD

**Comment by AduosPiggy** [comment]
> [@AduosPiggy](https://github.com/AduosPiggy) upgrade to ubuntu 20 bro, it will solve xD

bro,thank u! 
but my env: ubuntu22.04.4 + android15r17; 
mabey it caused by network proxy or google service crash, something didn't download.
finally solved by following *zip*：
https://pan.baidu.com/s/1JdKF5n2-mfgBiTJkx6rEdg?pwd=zanm 提取码: zanm 

plus some solve method, website:
google：https://source.android.com/docs/devices/cuttlefish/get-started?hl=zh-cn
https://juejin.cn/post/7343138429939269651
https://juejin.cn/post/7397013935104770099
https://blog.ohaiya.com/2024/10/29/ubuntu-install-cuttlefish/
